server.port: 9010
spring.jpa.hibernate.ddl-auto: none
spring.datasource.url: jdbc:mysql://localhost:3306/db_clipSelect
spring.datasource.username: springuser
spring.datasource.password: ThePassword
spring.mail.host: smtp.gmail.com
spring.mail.port: 587
spring.mail.username: clipselect1@gmail.com
spring.mail.password: shriramclipselect
spring.mail.properties.mail.smtp.starttls.enable: true
spring.mail.properties.mail.smtp.starttls.required: true
spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.smtp.connectiontimeout: 5000
spring.mail.properties.mail.smtp.timeout: 5000
spring.mail.properties.mail.smtp.writetimeout: 5000
#https://spring.io/guides/gs/accessing-data-mysql/
#spring.jpa.hibernate.ddl-auto: create
#create database db_clipSelect;
#create user 'springuser'@'localhost' identified by 'ThePassword';
#grant all on db_clipSelect.* to 'springuser'@'localhost';
#revoke all on db_clipSelect.* from 'springuser'@'localhost';
#grant select, insert, delete, update on db_clipSelect.* to 'springuser'@'localhost';
#mysql - root/admin
#use db_clipSelect;
#insert into zip_code_wind_zone values ("1234", "1");
#insert into concrete_details (sno, mfr, roof_tile, length, width, no_of_tile) values ("1", "a", "a1", "1", "2", "3");
#insert into concrete_details (sno, mfr, roof_tile, length, width, no_of_tile) values ("2", "a", "a2", "10", "20", "30");
#insert into concrete_details (sno, mfr, roof_tile, length, width, no_of_tile) values ("3", "b", "b1", "4", "5", "6");
#insert into concrete_details (sno, mfr, roof_tile, length, width, no_of_tile) values ("4", "b", "b2", "40", "50", "60");
#insert into concrete_details (sno, mfr, roof_tile, length, width, no_of_tile) values ("5", "c", "c1", "7", "8", "9");
#insert into concrete_details (sno, mfr, roof_tile, length, width, no_of_tile) values ("6", "c", "c2", "70", "80", "90");